# Generated by Django 3.0.14 on 2022-02-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220208_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classnet_cetification', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='classnet_certification',
        ),
    ]
