# Generated by Django 3.0.14 on 2022-02-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220210_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='classnet',
            name='classnetid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='classnet',
            name='classnetpw',
            field=models.CharField(default='', max_length=100),
        ),
    ]
