# Generated by Django 3.0.14 on 2022-02-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220210_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AlterField(
            model_name='classnet',
            name='classnetid',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
