# Generated by Django 3.0.14 on 2022-02-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220211_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classnet_id',
            field=models.CharField(default='', error_messages={'unique': '이미 인증된 Classnet 계정입니다.'}, max_length=100, unique=True),
        ),
    ]
