# Generated by Django 3.0.14 on 2022-02-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220211_0249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='classnet_id',
            new_name='classnetId',
        ),
    ]
