# Generated by Django 3.0.14 on 2022-02-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepost',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='moviepost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviepost',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='moviepost',
            name='updated_at',
        ),
    ]
