# Generated by Django 3.0.14 on 2022-01-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movie_pubDate',
            field=models.CharField(max_length=20),
        ),
    ]
