# Generated by Django 3.0.14 on 2022-03-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220227_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='movie_actor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='moviepost',
            name='movie_actor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='moviepost',
            name='movie_director',
            field=models.CharField(default='', max_length=30),
        ),
    ]
