# Generated by Django 3.0.14 on 2022-01-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220123_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo',
            name='movie_subtitle',
        ),
    ]
