# Generated by Django 3.0.14 on 2022-03-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20220306_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviepost',
            name='updated_at',
        ),
    ]
