# Generated by Django 3.0.14 on 2022-03-06 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20220306_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepost',
            name='movie_actor',
        ),
    ]
